export const DASHBOARD_CONSTANTS = {
  MESSAGES: {
    LINK_MINIMIZED_SUCCESS: "✨ Link crafted successfully!",
    LINK_MINIMIZED_ERROR: "Oops — couldn't generate your link.",
    LINK_ERASED_SUCCESS: "Link permanently removed.",
    LINK_ERASED_ERROR: "Failed to remove link.",
    LINK_COPIED_SUCCESS: "📋 Copied to clipboard!",
    LINK_COPIED_FALLBACK: "Link copied to clipboard.",
  },
  MENU: {
    OVERALL_LINKS: "Dashboard",
    HISTORY_LOG: "My Links",
  },
  MODAL: {
    QR_SCANNER: "Your QR Code",
  },
  HERO: {
    HEADING_LINE_1: "Shrink.",
    HEADING_LINE_2: "Track. Dominate.",
    SUBTEXT: "Paste any URL and turn it into a powerful trackable micro-link in seconds",
  },
  FORM: {
    LABEL: "Drop your link here",
    PLACEHOLDER: "Paste any long URL here...",
    BUTTON_LOADING: "Crafting...",
    BUTTON_DEFAULT: "Shrink It",
    ADVANCED_OPTIONS: "Advanced Options",
    PASSWORD: "Password Lock",
    MAX_CLICKS: "Click Limit",
    EXPIRY_DATE: "Self-Destruct Timer",
    PREVIEW_TITLE: "Link Preview",
    TAGS: "Tags",
    CATEGORY: "Category",
    COMMENT: "Note",
    CUSTOM_DOMAIN: "Custom Domain",
    TAGS_PLACEHOLDER: "marketing, social, launch...",
    CATEGORY_PLACEHOLDER: "e.g. Marketing",
    COMMENT_PLACEHOLDER: "Add a private note...",
    DOMAIN_PLACEHOLDER: "brand.link",
  },
  PERFORMANCE: {
    HEADING: "Analytics Overview",
    OVERALL_CLICKS: "Total Clicks",
    ACTIVE_LINKS: "Active Links",
    AVG_CLICKS: "Avg. per Link",
    TRAFFIC_FORECAST: "Clicks Over Time",
    TOP_PERFORMING: "Top Performers",
    LAST_7_DAYS: "Created This Week",
  },
  HISTORY: {
    HEADING: "My Links",
    TOTAL_LINKS: "All Links",
    NO_LINKS: "You haven't created any links yet. Try shrinking one above!",
    HEADER_SOURCE_TARGET: "Source & Target",
    HEADER_ANALYTICS: "Analytics",
    HEADER_CREATED: "Created",
    HEADER_OPERATIONS: "Actions",
    TOOLTIP_ANALYTICS: "View Stats",
    TOOLTIP_COPY: "Copy Link",
    TOOLTIP_QR: "QR Code",
    TOOLTIP_SHARE: "Share",
    TOOLTIP_DELETE: "Delete",
  },
  SUCCESS_POPUP: {
    TITLE: "Link Ready! 🚀",
    SUBTITLE: "Your micro-link is live and trackable",
    COPY_BUTTON: "Copy Link",
    VIEW_STATS: "View Stats",
    DONE: "Done",
  }
};
