export const HERO_HEADING = "Experience liftoff with the next-generation IDE";
export const HERO_BUTTON = "Get Started";
export const TRY_IT_NOW_BUTTON = "Try it now";
export const PLAY_INTRO = "Play intro";
export const DOWNLOAD = "Download";
export const LOGIN = "Login";
export const DOCS = "Docs";
export const SHORTEN = "Shorten";
export const YOU_CAN_CREATE_MORE_LINKS = "5 free links left — sign up for unlimited";
export const YOU_CAN_CREATE_MORE_LINKS_TOOLTIP = "Guest users can create up to 5 links. Register for unlimited access.";
export const HERO_SUBTEXT = "Jugaadlink is a clever, high-performance URL management platform that streamlines your online experience."
export const HERO_HEADING_DASHBOARD = "Shorten Your Loooong Links :)"
export const DONT_HAVE_AN_ACCOUNT = "Don't have an account?"
export const REGISTER_NOW = "Register now"
export const REGISTER = "Create Account"
export const ALREADY_HAVE_AN_ACCOUNT = "Already have an account?"
export const LOGIN_NOW = "Login now"
export const REGISTRATION_SUCCESSFUL = "🎉 Account created! Please sign in."
export const REGISTRATION_FAILED = "Registration failed"
export const LOGIN_SUCCESSFUL = "Welcome back! 👋"
export const LOGIN_FAILED = "Invalid credentials. Try again."
